apiVersion: v1
kind: Service
metadata:
  name: librago-service
spec:
  selector:
    app: librago
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8000
      nodePort: 32000
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name: http
      port: 3306
      targetPort: 3306